apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-log-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/chetansingh/Working_Directory/POC_Application/Backend/Logs/Backend/Audit_log"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-log-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
