apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      # nodePort: 30001
      targetPort: 8080
  type: LoadBalancer
apiVersion: v1